# Route custom domains to different app engine services, otherwise all custom
# domains will route to the default service.
dispatch:
  - url: "track.consensus.app/*"
    service: analytics-proxy

  - url: "www.track.consensus.app/*"
    service: analytics-proxy

  - url: "labeling.consensus.app/*"
    service: labeling

  - url: "www.labeling.consensus.app/*"
    service: labeling

  - url: "staging.consensus.app/*"
    service: staging-frontend

  - url: "www.staging.consensus.app/*"
    service: staging-frontend

  - url: "dev.consensus.app/*"
    service: default

  - url: "www.dev.consensus.app/*"
    service: default

  - url: "consensus.app/*"
    service: production-frontend

  - url: "www.consensus.app/*"
    service: production-frontend
