[GLOBAL]
# Colors often work in CI, but the shell is usually not a TTY so Pants
# doesn't attempt to use them by default.
colors = true

[test]
use_coverage = true

[coverage-py]
report = ["xml"]
global_report = true

[pytest]
args = ["-vv", "--no-header"]

[docker]
env_vars = ["DOCKER_BUILDKIT=1", "GCLOUD_PROJECT_ID='consensus-334718'"]
default_repository = "{name}"
build_args = ["GIT_COMMIT", "GCLOUD_PROJECT_ID", "LATEST_BRANCH_TAG"]

[docker.registries.gcr]
address = "gcr.io/consensus-334718"
default = true
