[tool.black]
line-length = 99

[tool.isort]
profile = "black"
line_length = 99
color_output = true
force_single_line = false

[tool.mypy]
namespace_packages = true
explicit_package_bases = true
mypy_path = "src/python"

no_implicit_optional = true
implicit_reexport = false
strict_equality = true

warn_unused_configs = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true

pretty = true
show_column_numbers = true
show_error_context = true
show_error_codes = true
show_traceback = true

[tool.pytest.ini_options]
addopts = "-s"
asyncio_mode = 'auto'

[[tool.mypy.overrides]]
module = "pyspark.pandas.plot.core"
follow_imports = "skip"

[[tool.mypy.overrides]]
module = "git"
implicit_reexport = true

[[tool.mypy.overrides]]
module = "nltk"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "nltk.corpus"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pylatexenc.latex2text"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "sentence_transformers"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "google.cloud"
ignore_missing_imports = true
