deployment:
  enabled: true
  revisionHistoryLimit: 3

serviceAccountName: github-actions

replicaCount: ${replicas}

service:
  enabled: true
  type: LoadBalancer
  ports:
    default:
      internal: 8080
      external: 8080
  annotations:
    cloud.google.com/load-balancer-type: "Internal"

ingress:
  default:
    enabled: true
    port: default
    annotations:
      kubernetes.io/ingress.class: "gce"
      kubernetes.io/ingress.global-static-ip-name: "${env}-track-ip"
      cert-manager.io/cluster-issuer: cluster-issuer-prod
      acme.cert-manager.io/http01-edit-in-place: "true"
      cert-manager.io/issue-temporary-certificate: "true"
      beta.cloud.google.com/backend-config: '{"default": "be-config"}'
    hosts:
      "${hostenv}track.k8s.consensus.app": /*
    tls:
    - secretName: "${env}-track-tls"
      hosts:
      - "${hostenv}track.k8s.consensus.app"
      - "${hostenv}track.consensus.app"
      - "www.${hostenv}track.consensus.app"

configMaps:
  default:
    enabled: true
    env:
      FE_WEB_BACKEND_URI: "http://${env}-web-backend-monochart.${namespace}.svc.cluster.local:8080"
      FE_DEPLOYMENT_ENV: "${namespace}"

resources:
  limits:
    cpu: ${cpu_limit}
    memory: ${memory_limit}
  requests:
    cpu: ${cpu_request}
    memory: ${memory_request}

probes:
  livenessProbe:
    httpGet:
      path: /
      port: 8080
    periodSeconds: 15
    timeoutSeconds: 4
    failureThreshold: 4
    successThreshold: 1

  startupProbe:
    httpGet:
      path: /
      port: 8080
    periodSeconds: 10
    timeoutSeconds: 4
    failureThreshold: 30
    successThreshold: 1
