import Head from "next/head";
import Link from "next/link";
import {
  listSearchTestingMetricFiles,
  listToAnnotateFiles,
} from "util/question_answer_annotations/storage";
import { getBaseName } from "util/storage";

interface HomeProps {
  metricFileNames: string[];
  toAnnotateMap: { [fileName: string]: boolean };
}

export default function Home({ metricFileNames, toAnnotateMap }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex bg-white">
        <div className="flex flex-col p-4">
          <h1>Search Testing Metrics</h1>
          {metricFileNames.map((file) => (
            <div key={file} className="flex flex-row">
              <Link className="pl-4 text-blue-600" href={`/metrics/${file}/`} legacyBehavior>
                {file}
              </Link>
              {toAnnotateMap[file] && (
                <Link
                  className="pl-4 text-blue-600"
                  href={`/annotations/qa/${file}/`}
                >
                  {"(to_annotate)"}
                </Link>
              )}
            </div>
          ))}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const toAnnotateFiles = await listToAnnotateFiles();
  const metricFiles = await listSearchTestingMetricFiles();
  const metricFileNames = metricFiles.map(getBaseName);

  const toAnnotateMap: { [fileName: string]: boolean } = {};
  for (const toAnnotate of toAnnotateFiles) {
    const file = getBaseName(toAnnotate);
    toAnnotateMap[file] = true;
  }

  return { props: { metricFileNames, toAnnotateMap } };
}
